### ISSUE TITLE
MacOS: VoiceOver Utility - "Verbosity -> Hints -> Speak instructions" enabled by default

### ISSUE THREAD

**Issue by nmerget** [guidepup/setup#30]
# "Verbosity -> Hints -> Speak instructions" enabled by default

Setup:

- NPM version: all
- OS Platform: macos
- OS Release: latest (CI)

## Details

@cmorten @jlp-craigmorten, first of all, thanks for your work :)

We are testing guidepup and there is some option for voiceOver which might be a little bit annoying.
You can see it [here](https://github.com/db-ui/evaluations/actions/runs/8814008833/artifacts/1442588664) the output is:

``["Label. You are currently on a text element, inside of web content. To exit this web area, press Control-Option-Shift-Up Arrow.","Label (Default) Basic edit text. You are currently on a text field, inside of web content. To enter text in this field, type. To exit this web area, press Control-Option-Shift-Up Arrow."]``

The default voiceOver config enables speak instructions for items ("You are currently on a text element, inside of web content. To exit this web area, press Control-Option-Shift-Up Arrow"). It would be great if we could optin/out the checkbox under VoiceOver Utility - "Verbosity -> Hints -> Speak instructions" on our CI, maybe like this:

````yml
      - name: 🦮 Guidepup Setup
        uses: guidepup/setup-action@0.15.x
        with:
          enableSpeakInstructions: false
````
